location = /vibz-admin { return 302 https://35.247.217.66.nip.io/vibz/; }
location /vibz-admin/ { return 302 https://35.247.217.66.nip.io/vibz/; }
location = /vibz { return 301 https://35.247.217.66.nip.io/vibz/; }
location /vibz/ { return 301 https://35.247.217.66.nip.io$request_uri; }
